name: bot-signoff

"on":
  pull_request:
  workflow_dispatch:

jobs:
  signoff:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.TERO_BOT_CLIENT_ID }}
          private-key: ${{ secrets.TERO_BOT_PRIVATE_SIGNING_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - run: git config --global url.https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/.insteadOf https://github.com/

      - uses: cashapp/activate-hermit@v1
      - run: task signoff
